### ISSUE TITLE
Could you release ai2d.json and vqa.json ?

### ISSUE THREAD

**Issue by xue-xiaobao** [expertailab/ISAAQ#1]
as shown at https://github.com/expertailab/ISAAQ/blob/master/pretrainings/aux_methods.py#L336

and

https://github.com/expertailab/ISAAQ/blob/master/pretrainings/aux_methods.py#L260

**Comment by rortegagit** [comment]
We have updated the jsons.zip file. Try to download it again. 

Thanks.
