### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers.modeling_roberta'

### ISSUE THREAD

**Issue by MALLI7622** [expertailab/ISAAQ#3]
I am getting this error after running the code but didn't find the line in the code files

**Comment by rortegagit** [comment]
Hi, please try installing the transformers package with the version published on the dependencies section (pip install transformers==2.11.0)

**Comment by Sosycs** [comment]
@MALLI7622 was it solved at your end? I would appreciate the help if it did!
Thanks in advance
